import Menu from "@/components/menu";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Dropbox",
	description: "Generated by create next app",
};


export default function Home() {
	return (

		<main>
			<Menu />
		</main>

	);
}
